site_name: Improved Addon Documentation | SCP:RP
site_url: https://cifiuqa.github.io/addon-docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: blue
  features:
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
  logo: assets/logo.png
  favicon: assets/logo.png

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/cjHvAwGQY5

extra_css:
  - assets/css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - toc:
      permalink: true
