site_name: Better Addon Docs | SCPRP
site_url: http://cifiuqa.github.io/addon-docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
    - navigation.instant
    - content.code.copy
  logo: assets/logo.png
  favicon: assets/logo.png

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/cjHvAwGQY5
      name: The Aquifer
  generator: false

extra_css:
  - assets/css/extra.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
plugins:
  - blog:
      blog_dir: blog
      archive: false
  - search

nav:
  - index.md
  - docs.md
  - roblox.md
  - examples.md
  - Blog:
    - blog/index.md
copyright: This documentation is made by members of The Aquifer. You can join the server on the right!